### ISSUE TITLE
Contrato Cafeteria Magnate 3.0

### ISSUE THREAD

**Issue by magaly1311** [SistemasTecTlaxiaco/Cafeter-a-MAGNATE3.0#14]
[Contrato de desarrollo de software.pdf](https://github.com/SistemasTecTlaxiaco/Cafeter-a-MAGNATE3.0/files/13620305/Contrato.de.desarrollo.de.software.pdf)

**Comment by josealfredo79** [comment]
45 calificacion ...bien hecho
